# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56b93546cb2f42356060af44593bec399d858a213099b741b0d73c818d551035a015195bc3f6e4d4132431b97322ab6b0678bf56ade315951dc9880ab9df36c4

test:
  secret_key_base: dea33ac6ff79624c7b51caa0236c944507637076a776384a6e0029da1cfb32078f624773e16abbedf94a95005505a38b83a5f73318393d1550bb114a07fde891

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
